Ag:
  Event:
    eventHandlers:
      sync:
        - 'Ag\Shop\Inventory\EventHandler\EventHandler'
        - 'Ag\Shop\Billing\EventHandler\EventHandler'
        - 'Ag\Shop\Cache\EventHandler\EventHandler'